Nota1 = "HOLA GRACIAS POR BRINDARNOS TU CONFIANZA AL ADQUIRIR TUS PRODUCTOS CON NOSOTROS, NUESTRO PRINCIPAL COMPROMISO ES BRINDAR TUS PRODUCTOS EN TIEMPO Y FORMA."
Nota2 = "TE RECORDAMOS QUE LOS PAGOS CON LOS DIAS 16/06 Y EL 01/07"
Nota3 = "TUS PAGOS PUEDEN SER EN EFECTIVO, PAGO CON TARJETA, TRANSFERECIA O EN LINEA"

	document.getElementById('Notas1').innerHTML = Nota1
	document.getElementById('Notas2').innerHTML = Nota2
	document.getElementById('Notas3').innerHTML = Nota3




